name: Build Docker Images

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image-tag: [
          3.8.6-openjdk-8-slim,
          3.8.6-openjdk-11-slim,
          3.6.3-openjdk-14-slim,
          3.8.1-openjdk-15-slim,
          3.8.3-openjdk-16-slim,
          3.8.5-openjdk-17-slim,
          3.8.7-openjdk-18-slim,
        ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | base64 --decode | docker login --username toodleloo --password-stdin
          export BASE_IMAGE_TAG="${{ matrix.base-image-tag }}"
          IMAGE_NAME="toodleloo/maven-aws:${BASE_IMAGE_TAG}"
          DOCKERFILE_CONTENTS=$(envsubst < Dockerfile.template)
          echo "$DOCKERFILE_CONTENTS"
          docker build -t "$IMAGE_NAME" - <<< "$DOCKERFILE_CONTENTS"
          docker push "$IMAGE_NAME"
